### ISSUE TITLE
What is this?

### ISSUE THREAD

**Issue by zkmoney** [Clivern/Beetle#130]
This project looks very cool, and is speaking my language (I think) when it comes to solving a very real need that I have experienced when running applications on k8s. But, back to the "I think" from above... what exactly is it? Is it meant to compete with something like Helm? Does it use/interoperate with Helm? Is it a wrapper around Helm? Is it a wrapper around the terraform k8s plugin? Is it a service harness/chassis/runtime and a central server and some other glue for introspection on running/apps deployments (the example config file makes me feel like it might be something like that... but I honestly can't tell from the README...) 

Anyway, saw this on the Changelog newsletter, and I'm intrigued... but I still am not really sure what it is. 

So I guess my feature request would be a section in the README that explains that.

**Comment by Clivern** [comment]
Hello @zkmoney,

Beetle is a way to automate k8s deployment directly from git (a.k.a GitOps https://www.weave.works/technologies/gitops/).
All i wanted is to create a service that can upgrade a running application on cluster `x` and namespace `y` with different deployment strategies.

terraform operator used to interact with beetle api server. But with the REST api definition you can build you own thing. for example deploy from a slack bot or a dashboard. 
```
# slack command
/beetle deploy version $$1.0.0 $$myapp cluster $$production namespace $$default
```
and use beetle webhook to inform you back once the deployment finish. Beetle will take care of the deployment.

You can achieve the same results with helm, fluxcd or even updating k8s yaml files manually. It is more about what fits perfectly in your workflow since all these tools trying to solve the same problem (k8s deployment automation). I am considering a blog post to explain beetle and how to use it.
